INSERT EMPLOYEE (Fname,Minit,Lname,Ssn,Bdate,Address,Sex,Salary,Super_ssn,Dno)

VALUES

('EZDEL','4','OLID','1','2004-01-04','lagumbingan','M','2003','01','07'),
('EZDEL','4','OLID','2','2004-01-04','lagumbingan','M','2003','01','07'),
('EZDEL','4','OLID','3','2004-01-04','lagumbingan','M','2003','01','07'),
('EZDEL','4','OLID','4','2004-01-04','lagumbingan','M','2003','01','07'),
('EZDEL','4','OLID','5','2004-01-04','lagumbingan','M','2003','01','07')
SELECT * FROM EMPLOYEE
--REVERSE
SELECT * FROM EMPLOYEE ORDER BY Ssn DESC;



--FOR FOREIGN-KEY
select EMPLOYEE.*, DEPARTMENT.*
from EMPLOYEE
right join DEPARTMENT
on EMPLOYEE.Ssn = DEPARTMENT.Mgr_ssn


SELECT EMPLOYEE.Address, DEPARTMENT.Dname
FROM EMPLOYEE
LEFT JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT.Mgr_ssn


SELECT EMPLOYEE.*, DEPARTMENT.*
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.Ssn = DEPARTMENT.Mgr_ssn



UPDATE EMPLOYEE
SET Fname = 'EDZEL'
WHERE Ssn = 1


--DELETE ALL
DELETE FROM EMPLOYEE


--ONE OR MORE
DELETE FROM EMPLOYEE
where Ssn = 2

